name: Test / Build / Release

on:
  push:
    branches:
      - homolog

permissions:
  contents: write
  id-token: write

jobs:
  release-homolog:
    name: Release-homolog
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      PROJECT_ID: fastech-homolog
      REGISTRY: gcr.io

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_HOMOLOG }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker ${{ env.REGISTRY }} -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
          SHORT_SHA=${GITHUB_SHA::7}

          docker buildx build \
            --build-arg GITHUB_TOKEN=${{ secrets.RELEASE_GH_TOKEN }} \
            --build-arg GIT_COMMIT_HASH=$SHORT_SHA \
            -t $IMAGE:$SHORT_SHA \
            -t $IMAGE:homolog \
            --push .

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Show pushed tags
        run: |
          echo "✅ Pushed:"
          echo " - $IMAGE:$SHORT_SHA"
          echo " - $IMAGE:homolog"